// <auto-generated />
namespace GraciousGrocery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class shoppingCart_submitedProducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shoppingCart_submitedProducts));
        
        string IMigrationMetadata.Id
        {
            get { return "202102021503104_shoppingCart_submitedProducts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
